package info.deakekure;

/**
 * Contract for object which hold credential's policy item. For simplicity, only
 * add two policy item.
 * 
 * @author zakyalvan
 */
public interface CredentialsPolicy {
	/**
	 * Policy item determine whether password must be force generated by system
	 * on each user registration or not.
	 * 
	 * @return
	 */
	boolean alwaysGenerateOnRegistration();
	
	/**
	 * Policy item determine default strategy of password generator.
	 * 
	 * @return
	 */
	Class<PasswordGenerator> defaultPasswordGeneratorType();
}
